### ISSUE TITLE
Factory / Storage task list

### ISSUE THREAD

**Issue by DavidEdwards** [DavidEdwards/EVE-PI#40]
There were a bunch of issues relating to essentially the same thing. Since CCP has released contents data, I can start working on all of them. Instead of having several issues, I intend to condense them into one.

- [x] List cached progress of factories
- [x] List cached storage contents
- [ ] List estimated REAL progress of factories
- [ ] List estimated REAL storage contents
- [ ] Add alerts for factories not running too often
- [ ] Add alerts for storage reaching X% full
- [ ] Evaluate value (isk) of factories / storage
- [ ] Full simulation of entire colony over time. Predictive analytics. Improvement suggestions.

**Comment by DavidEdwards** [comment]
Version 1.3 releasing today will show the cached information provided from ESI. Future versions will work on simulating the data.
